import { ReactNode } from 'react';
import Head from 'next/head';
import type { NextPage } from 'next';

import Header from 'components/Header';
import Menu from 'components/Menu';
import Comments from 'components/Comments';

interface IProps {
  children: ReactNode;
  hideComments?: boolean;
  hideMenu?: boolean;
  className?: string;
}

const MainLayout: NextPage<IProps> = ({
  children,
  hideComments = false,
  hideMenu = false,
  className = '',
}) => (
  <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet"
      />
    </Head>
    <Header />
    <div className={`container${className ? ` ${className}` : ''}`}>
      {!hideMenu && <Menu />}
      <div>{children}</div>
      {!hideComments && <Comments />}
    </div>
  </>
);

export default MainLayout;
